// src/featuredProductsData.js
export const featuredProducts = [
  {
    id: 101,
    brand: 'adidas',
    name: 'Cartoon Astronaut T-Shirt',
    price: 78,
    rating: 5,
    image: '../images/products/f1.jpg',
  },
  {
    id: 102,
    brand: 'H&M',
    name: 'Green Leaf Pattern Shirt',
    price: 65,
    rating: 5,
    image: '../images/products/f2.jpg',
  },
  {
    id: 103,
    brand: 'Zara',
    name: 'Rose Floral Summer Shirt',
    price: 72,
    rating: 5,
    image: '../images/products/f3.jpg',
  },
  {
    id: 104,
    brand: 'Prada',
    name: 'White Flower T-Shirt',
    price: 85,
    rating: 5,
    image: '../images/products/f4.jpg',
  },
  {
    id: 105,
    brand: 'Gucci',
    name: 'Violet Blossom T-Shirt',
    price: 92,
    rating: 5,
    image: '../images/products/f5.jpg',
  },
  {
    id: 106,
    brand: 'Levi\'s',
    name: 'Two-Tone Denim Jacket',
    price: 115,
    rating: 5,
    image: '../images/products/f6.jpg',
  },
  {
    id: 107,
    brand: 'Calvin Klein',
    name: 'Beige Casual Trousers',
    price: 88,
    rating: 5,
    image: '../images/products/f7.jpg',
  },
  {
    id: 108,
    brand: 'Tommy Hilfiger',
    name: 'Stylish Cat Blouse',
    price: 68,
    rating: 5,
    image: '../images/products/f8.jpg',
  },
];