// src/newArrivalsData.js
export const newArrivals = [
  {
    id: 201,
    brand: 'H&M',
    name: 'Light Blue Cotton Shirt',
    price: 85,
    rating: 5,
    image: '/images/products/n1.jpg',
  },
  {
    id: 202,
    brand: 'Zara',
    name: 'Gray Plaid Formal Shirt',
    price: 95,
    rating: 5,
    image: '/images/products/n2.jpg',
  },
  {
    id: 203,
    brand: 'adidas',
    name: 'Classic White T-Shirt',
    price: 60,
    rating: 5,
    image: '/images/products/n3.jpg',
  },
  {
    id: 204,
    brand: 'Prada',
    name: 'Army Print T-Shirt',
    price: 78,
    rating: 5,
    image: '/images/products/n4.jpg',
  },
  {
    id: 205,
    brand: 'Levi\'s',
    name: 'Simple Blue Denim Shirt',
    price: 110,
    rating: 5,
    image: '/images/products/n5.jpg',
  },
  {
    id: 206,
    brand: 'Gucci',
    name: 'Gray Shorts',
    price: 98,
    rating: 5,
    image: '/images/products/n6.jpg',
  },
  {
    id: 207,
    brand: 'Calvin Klein',
    name: 'Brown Long Sleeve Shirt',
    price: 89,
    rating: 5,
    image: '/images/products/n7.jpg',
  },
  {
    id: 208,
    brand: 'Tommy Hilfiger',
    name: 'Ash Short Sleeve Shirt',
    price: 70,
    rating: 5,
    image: '/images/products/n8.jpg',
  },
];